### ISSUE TITLE
 cannot open file 'renv/activate.R': No such file or directory when using renv

### ISSUE THREAD

**Issue by PhilippeRacicot** [mdneuzerling/ReviewSentiment#30]
I get this error when I run the exact same rcmdcheck workflow as yours :

In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory

**Comment by PhilippeRacicot** [comment]
You need to make sure renv have generated the renv folder in your project :
https://github.com/mdneuzerling/ReviewSentiment/tree/trunk/renv

**Comment by mdneuzerling** [comment]
Oh good point! I've added a note to use `renv::activate()` in the blog post. Thank you!
